# Generated by Django 5.1.3 on 2024-11-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SAIDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=16)),
                ('citizenship_status', models.CharField(max_length=20)),
                ('search_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(max_length=50)),
                ('id_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idvault.saidrecord')),
            ],
        ),
    ]
